### ISSUE TITLE
FYI: mace==0.3.10 only works with cuequivariance==0.1.0

### ISSUE THREAD

**Issue by BurgerAndreas** [ACEsuit/mace#827]
In case you run into an error like:
```bash
  File ".../site-packages/mace/modules/wrapper_ops.py", line 102, in __new__
    instance = cuet.Linear(
TypeError: Linear.__init__() got an unexpected keyword argument 'optimize_fallback'
```

The answer (as of now) is to downgrade to `cuequivariance==0.1.0`
```bash
pip install cuequivariance==0.1.0 cuequivariance-torch cuequivariance-ops-torch-cu12
```

**Comment by BurgerAndreas** [comment]
If anyone wants to tackle upgrading MACE:

`optimize_fallback` was renamed to `use_fallback` in `cuequivariance==0.2.0`
https://github.com/NVIDIA/cuEquivariance/blob/v0.2.0/cuequivariance_torch/cuequivariance_torch/operations/linear.py#L53

but there are a couple of other things that have to be fixed as well, that I haven't looked into

**Comment by alinelena** [comment]
duplicate of #811

**Comment by ilyes319** [comment]
that is fixed in the develop branch.
