### ISSUE TITLE
MACE 0.3.9 can not jit compile model trained with previous versions

### ISSUE THREAD

**Issue by lohedges** [ACEsuit/mace#741]
It appears that the MACE models generated by version 0.3.9 aren't TorchScript compliant. To reproduce:

```python
import torch
from mace.calculators.foundations_models import mace_off

model = mace_off(return_raw_model=True)

script_model = torch.jit.script(model)
```

Gives (truncated):

```
...

RuntimeError:
Module 'reshape_irreps' has no attribute 'cueq_config' :
  File "/home/lester/.conda/envs/emle/lib/python3.10/site-packages/mace/modules/irreps_tools.py", line 89
            field = tensor[:, ix : ix + mul * d]  # [batch, sample, mul * repr]
            ix += mul * d
            if hasattr(self, "cueq_config") and self.cueq_config is not None:
                                                ~~~~~~~~~~~~~~~~ <--- HERE
                if self.cueq_config.layout_str == "mul_ir":
                    field = field.reshape(batch, mul, d)
```

The same error is triggered using `e3nn` to compile the model, e.g:

```python
from e3nn.util import jit

script_model = jit.compile(model)
```

This works fine with version 0.3.6, which is what I was using previously. For reference, I am using Python 3.10 on Linux x86 and installed `mace-torch` via `pip`.

Cheers.

**Comment by ilyes319** [comment]
What is your torch version? It is normal that the torch jit does not work.

I think it is just you can not compile old models but only models trained with 0.3.9 (we have tests for that). If you want to compile a model trained with an old version, that you need to use that version.

**Comment by lohedges** [comment]
Thanks, I'll check the `torch` version this evening and report back. This is just using your own MACE OFF models in a completely fresh environment, I'm not training anything.

**Comment by ilyes319** [comment]
Exactly, mace-off was trained with an older version of mace such that you can not compile it with 0.3.9. You need to use an older version, (probably anything up to 0.3.8). 
Any model trained with 0.3.9 will be able to be jit compiled with 0.3.9.

**Comment by ilyes319** [comment]
Unfortunately no, models at the time did not encode the version. You can still evaluate the model with the current version, just not jit compile.
I can probably fix that though in the next release to make even jit compile backward compatible. I ll ping you.

For now, I recommand you to just compile using 0.3.6, and save the compiled model somewhere.

**Comment by lohedges** [comment]
Thanks, no problem. I'll just add a pin for now.

**Comment by lohedges** [comment]
Just to confirm that, as suggested, MACE-OFF works with MACE up to and including version 0.3.8.

> I can probably fix that though in the next release to make even jit compile backward compatible. I ll ping you.

Thanks, this would be really helpful. Our use case is to create a dual MACE-EMLE model at runtime (EMLE does the elecstrostatic embedding). We need it to be serializable so that it can be loaded with OpenMM-ML, or directly in C++. Having self-consistency between the version of MACE and MACE-OFF would be ideal.

**Comment by RokasEl** [comment]
@lohedges, while you wait for the update you can just load the state dict of the old model into an instance of the model with the latest MACE version.

```
calc = mace_off("medium", device="cuda")
model = calc.models[0]
z_table = calc.z_table
zs = z_table.zs
updated_model = ScaleShiftMACE(
    atomic_numbers=list(zs),
    atomic_energies=np.zeros(len(zs)), # will be loaded from the state dict
    num_elements=len(zs),
    atomic_inter_scale=model.scale_shift.scale,
    atomic_inter_shift=model.scale_shift.shift,
    **hypers.to_dict(),
)
updated_model.load_state_dict(model.state_dict())

from e3nn.util import jit
script_model = jit.compile(updated_model) # works fine!
```

For the medium mace_off the hyperparams are:
```
MACE_Hyperparameters(r_max=5.0, num_bessel=8, num_polynomial_cutoff=5, max_ell=3, num_interactions=2, interaction_cls_first='RealAgnosticInteractionBlock', interaction_cls='RealAgnosticResidualInteractionBlock', hidden_irreps='128x0e+128x1o', MLP_irreps='16x0e', avg_num_neighbors=18.41771125793457, correlation=3, gate='silu')
```

**Comment by ilyes319** [comment]
Thanks @RokasEl. One can even extract the hypers directly using:

``` 
calc = mace_off("medium", device="cuda")
source_model = calc.models[0]
config = extract_config_mace_model(source_model)
target_model = source_model.__class__(**config).to(device)
target_model.load_state_dict(source_model.state_dict())
from e3nn.util import jit
script_model = jit.compile(target_model)
````

**Comment by lohedges** [comment]
Brilliant, many thanks for this @RokasEl. I'll add this in now.

**Comment by lohedges** [comment]
Can confirm that this works perfectly. Thanks again for your help.

**Comment by ilyes319** [comment]
Should be fixed in the latest main now.

**Comment by lohedges** [comment]
Thanks for the update. I'll test when I get a chance.

**Comment by lohedges** [comment]
As of (I think) mace-torch 0.3.14 the [workaround](https://github.com/ACEsuit/mace/issues/741#issuecomment-2531144333) is no longer working:

```python
RuntimeError                              Traceback (most recent call last)
Cell In[2], line 1
----> 1 model = MACEEMLE()

File ~/Code/chemle/emle-engine/emle/models/_mace.py:218, in MACEEMLE.__init__(self, emle_model, emle_method, alpha_mode, mm_charges, qm_charge, mace_model, atomic_numbers, device, dtype)
    215 target_model = source_model.__class__(**config).to(device)
    217 # Load the state dict.
--> 218 target_model.load_state_dict(source_model.state_dict())
    220 # Compile the model.
    221 self._mace_models.append(_e3nn_jit.compile(target_model).to(self._dtype))

File ~/.conda/envs/emle/lib/python3.12/site-packages/torch/nn/modules/module.py:2581, in Module.load_state_dict(self, state_dict, strict, assign)
   2573         error_msgs.insert(
   2574             0,
   2575             "Missing key(s) in state_dict: {}. ".format(
   2576                 ", ".join(f'"{k}"' for k in missing_keys)
   2577             ),
   2578         )
   2580 if len(error_msgs) > 0:
-> 2581     raise RuntimeError(
   2582         "Error(s) in loading state_dict for {}:\n\t{}".format(
   2583             self.__class__.__name__, "\n\t".join(error_msgs)
   2584         )
   2585     )
   2586 return _IncompatibleKeys(missing_keys, unexpected_keys)

RuntimeError: Error(s) in loading state_dict for ScaleShiftMACE:
        Missing key(s) in state_dict: "products.0.symmetric_contractions.contractions.0.weights_0_zeroed", "products.0.symmetric_contractions.contractions.0.weights_1_zeroed", "products.0.symmetric_contractions.contractions.0.weights_max_zeroed", "products.1.symmetric_contractions.contractions.0.weights_0_zeroed", "products.1.symmetric_contractions.contractions.0.weights_1_zeroed", "products.1.symmetric_contractions.contractions.0.weights_max_zeroed". 
```

I assume that there are some new keys, which are missing in the old model. If this is the case, is it possible to set appropriate defaults when they are missing?

**Comment by lohedges** [comment]
Can confirm that the workaround still works with 0.3.13. Seems quite a surprising change for a patch release.

**Comment by ilyes319** [comment]
try doing target_model.load_state_dict(source_model.state_dict(), strict=False)

**Comment by ilyes319** [comment]
```
from mace.calculators import mace_off
from mace.tools.scripts_utils import extract_config_mace_model

device = "cpu"
calc = mace_off("medium", device=device)
source_model = calc.models[0]
config = extract_config_mace_model(source_model)
target_model = source_model.__class__(**config).to(device)
target_model.load_state_dict(source_model.state_dict(), strict=False)
from e3nn.util import jit
script_model = jit.compile(target_model)
```
this works

**Comment by lohedges** [comment]
Perfect, many thanks for the rapid response. Are there any risks to be aware of with this approach?

**Comment by ilyes319** [comment]
yes best is to make a test with a set of reference energies and forces and test them.

**Comment by ilyes319** [comment]
right now there is no worry to have, but for future update i recommend you do that kind of tests.

**Comment by lohedges** [comment]
Thanks, that's a good suggestion. I guess I was worried that this might open up the possibility of someone using a model trained with a new version of MACE for inference using an old version, whereas the workaround was to support the opposite. Having some single-point energy tests for standard MACE-OFF models would be a useful sanity check.

Thanks again for your help.
